# trade/settings.yaml

done_marker_reset_before: '21:00:00'

# trade_account: 'SPBFUT16qg3'  # Торговый счёт на срочном рынке

# trade_account: 'SPBFUT192yc'  # Торговый счёт на срочном рынке

accounts:
  iis:                                          # QUIK ИИС
    trade_filepath: 'C:/QUIK_VTB_2022_ИИС/algotrade/input.tri'
    trade_account: 'SPBFUT16qg3'
    rts:
      target_quantity: 0
    mix:
      target_quantity: 0
    ng:
      target_quantity: 0
    si:
      target_quantity: 0
    spyf:
      target_quantity: 0
  ebs:                                          # QUIK ЕБС
    trade_filepath: 'C:/QUIK_VTB_2025_ЕБС/algotrade/input.tri'
    # trade_filepath: 'C:/QUIK_VTB_2025_ЕБС/algotrade/test.tri'
    trade_account: 'SPBFUT192yc'
    rts:
      target_quantity: 2
      predict_dir: 'C:/Users/Alkor/gd/predict_ai/pj19/rts/combine'
    mix:
      target_quantity: 2
      predict_dir: 'C:/Users/Alkor/gd/predict_ai/pj19/mix/combine'
    ng:
      target_quantity: 0
    si:
      target_quantity: 0
    spyf:
      target_quantity: 0
